.MODEL FLAT,C
.DATA
 GA_SPACE EQU 22
 N=5
.CODE

STR_CMP    PROC FAR STDCALL USES EBX ECX EDX EDI ESI STR1_OFFSET:DWORD, STR2_OFFSET:DWORD,LEN:BYTE  
        
        MOVZX EBX,BYTE PTR LEN     ;修改为将LEN存入BX中作为倒数计数器
        MOV EDI, STR1_OFFSET
        MOV ESI, STR2_OFFSET
        
STR_CMP_LOOP:
        MOV CH, BYTE PTR  [EDI + EBX]
        MOV CL, BYTE PTR  [ESI + EBX]
        DEC EBX
		CMP CH,CL
		JNE UNEQUAL                  
		CMP EBX,0
		JGE STR_CMP_LOOP
		JMP EQUAL          
 UNEQUAL: 
        MOV EAX, 0
        RET   
 EQUAL:  
        MOV EAX, 1
        RET
STR_CMP ENDP

GET_PRO PROC STDCALL USES EBX ECX GA1OFF:DWORD,PRO:DWORD,LEN:BYTE
        MOV EBX,GA1OFF 
		MOV ECX, N
        MOV EDI,1

  LOOP1:      INVOKE STR_CMP, EBX, PRO,LEN
              CMP AX,1
			  JE RETURN
			  INC EDI
             ADD EBX, GA_SPACE
	    LOOP LOOP1
		MOV EAX,0
 RETURN: 
        RET
GET_PRO ENDP

Search_Pro proc
PUSH EBP
MOV EBP,ESP

INVOKE GET_PRO,[EBP+8],[EBP+12],BYTE PTR [EBP+16]

CMP EAX,0
JNE FOUND
MOV EAX,[EBP+20]
MOV [EAX],DWORD PTR 0
POP EBP
RET
FOUND:
MOV EAX,[EBP+20]
MOV [EAX],EDI
POP EBP
RET
Search_Pro endp

END
